<?php /** @noinspection SpellCheckingInspection */
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array(
    0                  =>
        array(
            'acceptable_sugar_versions' =>
                array(
                    0 => '',
                ),
        ),
    1                  =>
        array(
            'acceptable_sugar_flavors' =>
                array(
                    0 => 'PRO',
                ),
        ),
    'readme'           => '',
    'key'              => 'e8221',
    'author'           => 'Emil Maran',
    'description'      => 'e8221 SQL Reports for Sugar 6.5 Pro',
    'icon'             => '',
    'is_uninstallable' => true,
    'name'             => 'meSQLReports',
    'published_date'   => '2015-06-17 12:26:57',
    'type'             => 'module',
    'version'          => 1434544017,
    'remove_tables'    => 'prompt',
);

$installdefs = array(
    'id'            => 'meSQLReports',
    'beans'         =>
        array(
            0 =>
                array(
                    'module' => 'e8221_SQLReports',
                    'class'  => 'e8221_SQLReports',
                    'path'   => 'modules/e8221_SQLReports/e8221_SQLReports.php',
                    'tab'    => true,
                ),
        ),
    'layoutdefs'    =>
        array(),
    'relationships' =>
        array(),
    'image_dir'     => '<basepath>/icons',
    'copy'          =>
        array(
            0 =>
                array(
                    'from' => '<basepath>/SugarModules/modules/e8221_SQLReports',
                    'to'   => 'modules/e8221_SQLReports',
                ),
            // Custom Code @TODO
            1 =>
                array(
                    'from' => '<basepath>/custom/modules/e8221_SQLReports',
                    'to'   => 'custom/modules/e8221_SQLReports',
                ),
        ),
    'language'      =>
        array(
            0 =>
                array(
                    'from'      => '<basepath>/SugarModules/language/application/en_us.lang.php',
                    'to_module' => 'application',
                    'language'  => 'en_us',
                ),
        ),

    'logic_hooks' => array(
        array(
            'module'      => 'e8221_SQLReports',
            'hook'        => 'after_ui_frame',
            'order'       => 2,
            'description' => 'e8221_SQLReports',
            'file'        => 'custom/modules/e8221_SQLReports/SQLReportsLogicHook.php',
            'class'       => 'SQLReportsLogicHook',
            'function'    => 'CreateJsonData',
        ),
    )

);