<?PHP /** @noinspection SpellCheckingInspection */
/** @noinspection PhpUnused */
/** @noinspection PhpUndefinedClassInspection */
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN e8221_SQLReports
 */
class e8221_SQLReports_sugar extends Basic
{
    public $new_schema  = true;
    public $module_dir  = 'e8221_SQLReports';
    public $object_name = 'e8221_SQLReports';
    public $table_name  = 'e8221_sqlreports';
    public $importable  = true;
    public $id;
    public $name;
    public $date_entered;
    public $date_modified;
    public $modified_user_id;
    public $modified_by_name;
    public $created_by;
    public $created_by_name;
    public $description;
    public $deleted;
    public $created_by_link;
    public $modified_user_link;
    public $team_id;
    public $team_set_id;
    public $team_count;
    public $team_name;
    public $team_link;
    public $team_count_link;
    public $teams;
    public $team_sets;
    public $assigned_user_id;
    public $assigned_user_name;
    public $assigned_user_link;
    public $sqlgraph_type;
    public $sqlquery_text;
    public $sqljson_data;

    public function __construct()
    {
        parent::Basic();
    }

    public function bean_implements($interface)
    {
        return $interface === 'ACL';
    }

}

